// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShellController from "./shell_controller"
application.register("shell", ShellController)

import FieldMapController from "./field_map_controller"
application.register("field-map", FieldMapController)

import TripStatusController from "./trip_status_controller"
application.register("trip-status", TripStatusController)

import TripMapController from "./trip_map_controller"
application.register("trip-map", TripMapController)

import DriverFormController from "./driver_form_controller"
application.register("driver-form", DriverFormController)

import GastoFormController from "./gasto_form_controller"
application.register("gasto-form", GastoFormController)

import GastosChartController from "./gastos_chart_controller"
application.register("gastos-chart", GastosChartController)

import TripCalcController from "./trip_calc_controller"
application.register("trip-calc", TripCalcController)

import TripFormController from "./trip_form_controller"
application.register("trip-form", TripFormController)

import TripCalculatorController from "./trip_calculator_controller"
application.register("trip-calculator", TripCalculatorController)
