// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShellController from "./shell_controller"
application.register("shell", ShellController)

import FieldMapController from "./field_map_controller"
application.register("field-map", FieldMapController)

import TripStatusController from "./trip_status_controller"
application.register("trip-status", TripStatusController)

import TripMapController from "./trip_map_controller"
application.register("trip-map", TripMapController)

import TripCalculatorController from "./trip_calculator_controller"
application.register("trip-calculator", TripCalculatorController)
